import { useState, useEffect } from 'react';
import {
  getStore,
  addCategory,
  deleteCategory,
  addFrame,
  deleteFrame,
  setFrameLayout,
  getFrameLayout,
  getCategoryLayoutMap,
  downloadCategoryLayout,
  getPublishToken,
  DEFAULT_LAYOUT,
  currentAcademicYear,
  logout,
} from '../lib/adminStore';
import { publishLiveLayouts } from '../lib/liveLayouts';
import { loadFileCategories } from '../lib/frameManifest';
import FramePreviewEditor from './FramePreviewEditor';

export default function AdminDashboard({ onSignOut }) {
  const [store, setStore] = useState(getStore());
  const [fileCategories, setFileCategories] = useState({});
  const [activeCategory, setActiveCategory] = useState(Object.keys(store.categories)[0] || '');
  const [activeFrame, setActiveFrame] = useState(null);

  const [newCategoryLabel, setNewCategoryLabel] = useState('');
  const [newFrameLabel, setNewFrameLabel] = useState('');
  const [notice, setNotice] = useState('');

  // Categories derived from folders in public/ (see frames-manifest.json,
  // generated by vite-plugin-frame-manifest.js). Loaded once on mount —
  // reflects whatever folders/images currently exist on disk.
  useEffect(() => {
    let alive = true;
    loadFileCategories().then((cats) => {
      if (!alive) return;
      setFileCategories(cats);
      setActiveCategory((prev) => prev || Object.keys(cats)[0] || '');
    });
    return () => {
      alive = false;
    };
  }, []);

  function refresh(next) {
    setStore(next);
  }

  function handleAddCategory(e) {
    e.preventDefault();
    if (!newCategoryLabel.trim()) return;
    try {
      const next = addCategory(newCategoryLabel, newCategoryLabel);
      refresh(next);
      setNewCategoryLabel('');
      setNotice(`Category "${newCategoryLabel}" added. It now shows up for users.`);
    } catch (err) {
      setNotice(err.message);
    }
  }

  function handleDeleteCategory(key) {
    if (!confirm(`Delete category "${store.categories[key]?.label}"? This removes all its custom frames too.`)) return;
    const next = deleteCategory(key);
    refresh(next);
    if (activeCategory === key) setActiveCategory('');
    setActiveFrame(null);
  }

  function handleAddFrame(e) {
    e.preventDefault();
    const fileInput = e.target.elements.frameFile;
    const file = fileInput.files[0];
    if (!file || !activeCategory) return;
    const reader = new FileReader();
    reader.onload = (ev) => {
      const next = addFrame(activeCategory, {
        label: newFrameLabel || file.name,
        dataUrl: ev.target.result,
      });
      refresh(next);
      setNewFrameLabel('');
      fileInput.value = '';
      setNotice('Frame uploaded. It now shows up for users in this category.');
    };
    reader.readAsDataURL(file);
  }

  function handleDeleteFrame(categoryKey, frameId) {
    if (!confirm('Delete this frame?')) return;
    const next = deleteFrame(categoryKey, frameId);
    refresh(next);
    if (activeFrame?.id === frameId) setActiveFrame(null);
  }

  const customCategoryEntries = Object.entries(store.categories);
  const fileEntries = Object.entries(fileCategories);

  return (
    <div className="admin">
      <header className="admin__header">
        <div>
          <p className="mono admin__eyebrow">jrmsu · frame lab · admin</p>
          <h1 className="admin__title">Admin Dashboard</h1>
          <p className="admin__subtitle mono">{currentAcademicYear()}</p>
        </div>
        <div className="admin__header-actions">
          <a className="btn btn--ghost" href="#/">
            View app
          </a>
          <button
            className="btn btn--ghost"
            onClick={() => {
              logout();
              onSignOut();
            }}
          >
            Sign out
          </button>
        </div>
      </header>

      {notice && (
        <div className="banner banner--ok">
          {notice}{' '}
          <button className="admin__dismiss" onClick={() => setNotice('')}>
            ×
          </button>
        </div>
      )}

      <section className="admin__section">
        <h2>Categories</h2>
        <p className="admin__hint">
          Categories below "from folders" come straight from <code>public/</code> — add or delete
          a folder (and the images inside it) and it shows up here and for every user, no code
          changes needed. They can't be deleted from this dashboard since they live on disk; delete
          the folder itself instead. Categories you add below that are stored separately and can be
          removed here any time.
        </p>

        <div className="admin__category-grid">
          <div className="admin__category-list">
            <h3 className="mono">from folders (public/)</h3>
            {fileEntries.length === 0 && <p className="hint">No folders found yet.</p>}
            {fileEntries.map(([key, cfg]) => (
              <button
                key={key}
                className={`admin__category-item ${activeCategory === key ? 'is-active' : ''}`}
                onClick={() => {
                  setActiveCategory(key);
                  setActiveFrame(null);
                }}
              >
                {cfg.label}
              </button>
            ))}

            <h3 className="mono">custom (dashboard-added)</h3>
            {customCategoryEntries.length === 0 && <p className="hint">None yet.</p>}
            {customCategoryEntries.map(([key, cfg]) => (
              <div key={key} className="admin__category-row">
                <button
                  className={`admin__category-item ${activeCategory === key ? 'is-active' : ''}`}
                  onClick={() => {
                    setActiveCategory(key);
                    setActiveFrame(null);
                  }}
                >
                  {cfg.label}
                </button>
                <button
                  className="admin__delete-x"
                  title="Delete category"
                  onClick={() => handleDeleteCategory(key)}
                >
                  delete
                </button>
              </div>
            ))}

            <form className="admin__add-category" onSubmit={handleAddCategory}>
              <input
                type="text"
                placeholder="New category name (e.g. Graduation)"
                value={newCategoryLabel}
                onChange={(e) => setNewCategoryLabel(e.target.value)}
              />
              <button type="submit" className="btn btn--primary btn--sm">
                Add category
              </button>
            </form>
          </div>

          <div className="admin__frames-panel">
            {!activeCategory ? (
              <p className="hint">Pick a category on the left to manage its frames.</p>
            ) : (
              <FramesEditor
                categoryKey={activeCategory}
                isCustom={Boolean(store.categories[activeCategory])}
                builtInFrames={fileCategories[activeCategory]?.frames || []}
                customFrames={store.categories[activeCategory]?.frames || []}
                newFrameLabel={newFrameLabel}
                setNewFrameLabel={setNewFrameLabel}
                onAddFrame={handleAddFrame}
                onDeleteFrame={handleDeleteFrame}
                activeFrame={activeFrame}
                setActiveFrame={setActiveFrame}
              />
            )}
          </div>
        </div>
      </section>

      {activeFrame && (
        <LayoutEditor
          key={`${activeCategory}:${activeFrame.id}`}
          categoryKey={activeCategory}
          folder={fileCategories[activeCategory]?.folder || store.categories[activeCategory]?.folder || activeCategory}
          frame={activeFrame}
          onSaved={() => setNotice(`Layout saved for "${activeFrame.label}".`)}
        />
      )}
    </div>
  );
}

function FramesEditor({
  categoryKey,
  builtInFrames,
  customFrames,
  newFrameLabel,
  setNewFrameLabel,
  onAddFrame,
  onDeleteFrame,
  activeFrame,
  setActiveFrame,
}) {
  const BASE = import.meta.env.BASE_URL;
  return (
    <div>
      <h3>Frames in this category</h3>
      <div className="admin__frame-grid">
        {builtInFrames.map((f) => (
          <button
            key={f.id}
            className={`admin__frame-card ${activeFrame?.id === f.id ? 'is-active' : ''}`}
            onClick={() => setActiveFrame({ ...f, categoryKey })}
          >
            <img src={`${BASE}${categoryKey}/${f.file}`} alt={f.label} />
            <span className="mono">{f.label}</span>
            <span className="admin__frame-tag mono">from folder</span>
          </button>
        ))}
        {customFrames.map((f) => (
          <div key={f.id} className="admin__frame-card-wrap">
            <button
              className={`admin__frame-card ${activeFrame?.id === f.id ? 'is-active' : ''}`}
              onClick={() => setActiveFrame({ ...f, categoryKey })}
            >
              <img src={f.file} alt={f.label} />
              <span className="mono">{f.label}</span>
              <span className="admin__frame-tag mono">custom</span>
            </button>
            <button className="admin__delete-x" onClick={() => onDeleteFrame(categoryKey, f.id)}>
              delete
            </button>
          </div>
        ))}
      </div>

      <form className="admin__add-frame" onSubmit={onAddFrame}>
        <h4>Upload a static frame file (PNG, transparent hole + nameplate)</h4>
        <input
          type="text"
          placeholder="Frame label (e.g. Gold Trim)"
          value={newFrameLabel}
          onChange={(e) => setNewFrameLabel(e.target.value)}
        />
        <input type="file" name="frameFile" accept="image/png,image/*" />
        <button type="submit" className="btn btn--primary btn--sm">
          Upload frame
        </button>
      </form>
      <p className="admin__hint">
        Click any frame above to edit where the name/program print, their colors, and font style.
      </p>
    </div>
  );
}

function LayoutEditor({ categoryKey, folder, frame, onSaved }) {
  const [layout, setLayout] = useState(() => getFrameLayout(categoryKey, frame.id));
  const [publishState, setPublishState] = useState('idle'); // idle | publishing | done | error
  const [publishError, setPublishError] = useState('');

  function update(field, value) {
    setLayout((l) => ({ ...l, [field]: value }));
  }

  // One button, one action: save it for real. Writes the local draft AND
  // publishes it live in the same click — no separate "publish" step.
  async function handleSave(e) {
    e.preventDefault();
    setFrameLayout(categoryKey, frame.id, layout);
    setPublishState('publishing');
    setPublishError('');
    try {
      const fullMap = getCategoryLayoutMap(categoryKey);
      await publishLiveLayouts(folder, fullMap, getPublishToken());
      setPublishState('done');
      onSaved();
    } catch (err) {
      setPublishState('error');
      setPublishError(err.message);
    }
  }

  function handleBackupDownload() {
    setFrameLayout(categoryKey, frame.id, layout);
    downloadCategoryLayout(categoryKey, folder);
  }

  function handleResetDefaults() {
    setLayout(DEFAULT_LAYOUT);
  }

  function handleDragChange(patch) {
    setLayout((l) => ({ ...l, ...patch }));
  }

  return (
    <section className="admin__section">
      <h2>Text style</h2>
      <p className="admin__section-subtitle mono">{frame.label}</p>

      <FramePreviewEditor frame={frame} layout={layout} onChange={handleDragChange} />

      <form className="admin__layout-form" onSubmit={handleSave}>
        <fieldset>
          <legend>Name</legend>
          <label>
            Color
            <input type="color" value={layout.nameColor} onChange={(e) => update('nameColor', e.target.value)} />
          </label>
          <label>
            Font
            <select value={layout.nameFont} onChange={(e) => update('nameFont', e.target.value)}>
              <option value="display">Display (serif)</option>
              <option value="mono">Mono</option>
              <option value="sans">Sans</option>
            </select>
          </label>
          <label>
            Size (px)
            <input
              type="number"
              min="12"
              max="120"
              value={layout.nameSize}
              onChange={(e) => update('nameSize', Number(e.target.value))}
            />
          </label>
          <label>
            Position offset X
            <input
              type="number"
              value={layout.nameOffsetX}
              onChange={(e) => update('nameOffsetX', Number(e.target.value))}
            />
          </label>
          <label>
            Position offset Y
            <input
              type="number"
              value={layout.nameOffsetY}
              onChange={(e) => update('nameOffsetY', Number(e.target.value))}
            />
          </label>
        </fieldset>

        <fieldset>
          <legend>Program</legend>
          <label>
            Color
            <input
              type="color"
              value={layout.programColor}
              onChange={(e) => update('programColor', e.target.value)}
            />
          </label>
          <label>
            Font
            <select value={layout.programFont} onChange={(e) => update('programFont', e.target.value)}>
              <option value="display">Display (serif)</option>
              <option value="mono">Mono</option>
              <option value="sans">Sans</option>
            </select>
          </label>
          <label>
            Size (px)
            <input
              type="number"
              min="10"
              max="80"
              value={layout.programSize}
              onChange={(e) => update('programSize', Number(e.target.value))}
            />
          </label>
          <label>
            Position offset X
            <input
              type="number"
              value={layout.programOffsetX}
              onChange={(e) => update('programOffsetX', Number(e.target.value))}
            />
          </label>
          <label>
            Position offset Y
            <input
              type="number"
              value={layout.programOffsetY}
              onChange={(e) => update('programOffsetY', Number(e.target.value))}
            />
          </label>
        </fieldset>

        <div className="admin__layout-actions">
          <button type="submit" className="btn btn--primary" disabled={publishState === 'publishing'}>
            {publishState === 'publishing' ? 'Saving…' : 'Save position'}
          </button>
          <button type="button" className="btn btn--ghost" onClick={handleResetDefaults}>
            Reset to defaults
          </button>
          <button type="button" className="btn btn--ghost" onClick={handleBackupDownload}>
            Download backup copy
          </button>
        </div>
        {publishState === 'done' && (
          <p className="admin__hint" style={{ color: '#2a7a3b' }}>
            ✓ Saved. Everyone sees this now.
          </p>
        )}
        {publishState === 'error' && (
          <p className="admin__hint" style={{ color: '#b3261e' }}>
            ✗ Didn't save: {publishError}
          </p>
        )}
      </form>
      <p className="admin__hint">
        Drag the boxes above, or fine-tune with exact numbers below, then click{' '}
        <strong>Save position</strong>. That's it — one click, live for everyone immediately.
      </p>
    </section>
  );
}
